"""Static question bank — real exam-style questions for all 16 exam types.

Each exam type has questions across its subjects with varying difficulty.
Questions are modeled after actual exam patterns and official sample papers.
"""

from __future__ import annotations

QUESTIONS: dict[str, list[dict]] = {
    # =========================================================================
    # INDIA
    # =========================================================================
    "JEE Main": [
        # Physics
        {"subject": "Physics", "difficulty": "easy", "year": 2024, "source": "JEE Main 2024 Jan Shift 1",
         "question_text": "A ball is thrown vertically upward with a velocity of 20 m/s from the top of a building 25 m high. How long will it take for the ball to reach the ground? (g = 10 m/s²)",
         "options": {"A": "5 s", "B": "4 s", "C": "3 s", "D": "2 s"}, "correct_answer": "A",
         "explanation": "Using s = ut + ½gt², with s = -25m, u = 20 m/s, g = -10 m/s². We get -25 = 20t - 5t², solving 5t² - 20t - 25 = 0, t² - 4t - 5 = 0, (t-5)(t+1) = 0, t = 5s.",
         "tags": ["kinematics", "projectile"]},
        {"subject": "Physics", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024 Jan Shift 2",
         "question_text": "Two identical springs, each of spring constant k, are connected in series. A mass m is suspended from the combination. The time period of oscillation is:",
         "options": {"A": "2π√(2m/k)", "B": "2π√(m/2k)", "C": "2π√(m/k)", "D": "π√(m/k)"}, "correct_answer": "A",
         "explanation": "For springs in series, effective spring constant k_eff = k/2. Time period T = 2π√(m/k_eff) = 2π√(2m/k).",
         "tags": ["SHM", "springs"]},
        {"subject": "Physics", "difficulty": "hard", "year": 2023, "source": "JEE Main 2023 Apr Shift 1",
         "question_text": "An electron is moving in a circular orbit of radius r with speed v in a uniform magnetic field B perpendicular to the plane of the orbit. If the radius is doubled, the kinetic energy becomes:",
         "options": {"A": "4 times", "B": "2 times", "C": "Same", "D": "Half"}, "correct_answer": "A",
         "explanation": "r = mv/(eB), so v = eBr/m. KE = ½mv² = e²B²r²/(2m). If r → 2r, KE → 4 times.",
         "tags": ["magnetic field", "circular motion"]},
        {"subject": "Physics", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024 Sample",
         "question_text": "The moment of inertia of a uniform solid sphere about a tangent to the sphere is:",
         "options": {"A": "(7/5)MR²", "B": "(2/5)MR²", "C": "(5/3)MR²", "D": "(3/5)MR²"}, "correct_answer": "A",
         "explanation": "Using parallel axis theorem: I = I_cm + Md² = (2/5)MR² + MR² = (7/5)MR².",
         "tags": ["rotational mechanics", "moment of inertia"]},
        {"subject": "Physics", "difficulty": "easy", "year": 2023, "source": "JEE Main 2023",
         "question_text": "The SI unit of electric flux is:",
         "options": {"A": "N·m²/C", "B": "V·m", "C": "Both A and B", "D": "N/C"}, "correct_answer": "C",
         "explanation": "Electric flux Φ = E·A has units N·m²/C. Since V = J/C = N·m/C, V·m = N·m²/C. Both are equivalent.",
         "tags": ["electrostatics", "units"]},
        # Chemistry
        {"subject": "Chemistry", "difficulty": "easy", "year": 2024, "source": "JEE Main 2024 Jan",
         "question_text": "The IUPAC name of CH₃-CH=CH-CHO is:",
         "options": {"A": "But-2-enal", "B": "But-3-enal", "C": "2-Butenal", "D": "Crotonaldehyde"}, "correct_answer": "A",
         "explanation": "The compound is a 4-carbon chain with a double bond at C2 and an aldehyde group. IUPAC name: But-2-enal.",
         "tags": ["organic", "nomenclature"]},
        {"subject": "Chemistry", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024 Sample",
         "question_text": "The hybridization of xenon in XeF₄ is:",
         "options": {"A": "sp³d²", "B": "sp³d", "C": "sp³", "D": "dsp³"}, "correct_answer": "A",
         "explanation": "XeF₄ has 4 bond pairs and 2 lone pairs (6 electron domains), requiring sp³d² hybridization with square planar geometry.",
         "tags": ["chemical bonding", "hybridization"]},
        {"subject": "Chemistry", "difficulty": "hard", "year": 2023, "source": "JEE Main 2023 Apr",
         "question_text": "For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), if Kp = 1.6 × 10⁻⁴ at 400°C, the value of Kc is approximately: (R = 0.0821 L·atm/mol·K)",
         "options": {"A": "0.5", "B": "0.02", "C": "1.6 × 10⁻⁴", "D": "0.46"}, "correct_answer": "A",
         "explanation": "Kp = Kc(RT)^Δn. Δn = 2 - 4 = -2. T = 673K. Kc = Kp/(RT)^(-2) = Kp × (RT)² = 1.6×10⁻⁴ × (0.0821×673)² ≈ 0.5.",
         "tags": ["equilibrium", "thermodynamics"]},
        {"subject": "Chemistry", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024",
         "question_text": "Which of the following has the highest lattice energy?",
         "options": {"A": "MgO", "B": "NaCl", "C": "KBr", "D": "CaS"}, "correct_answer": "A",
         "explanation": "Lattice energy ∝ (q₁×q₂)/r. MgO has the highest charges (2+ and 2-) with small ionic radii, giving highest lattice energy.",
         "tags": ["ionic bonding", "lattice energy"]},
        # Mathematics
        {"subject": "Mathematics", "difficulty": "easy", "year": 2024, "source": "JEE Main 2024 Jan",
         "question_text": "The value of lim(x→0) (sin 5x)/(3x) is:",
         "options": {"A": "5/3", "B": "3/5", "C": "1", "D": "0"}, "correct_answer": "A",
         "explanation": "lim(x→0) sin(5x)/(3x) = lim(x→0) [sin(5x)/(5x)] × (5/3) = 1 × 5/3 = 5/3.",
         "tags": ["limits", "trigonometry"]},
        {"subject": "Mathematics", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024 Sample",
         "question_text": "If f(x) = x³ - 3x² + 3x - 1, then f'(1) equals:",
         "options": {"A": "0", "B": "1", "C": "3", "D": "-1"}, "correct_answer": "A",
         "explanation": "f'(x) = 3x² - 6x + 3. f'(1) = 3(1) - 6(1) + 3 = 0. Also note f(x) = (x-1)³.",
         "tags": ["differentiation", "polynomials"]},
        {"subject": "Mathematics", "difficulty": "hard", "year": 2023, "source": "JEE Main 2023",
         "question_text": "The area bounded by y = x², y = 0, and x = 2 is:",
         "options": {"A": "8/3", "B": "4/3", "C": "4", "D": "2"}, "correct_answer": "A",
         "explanation": "Area = ∫₀² x² dx = [x³/3]₀² = 8/3.",
         "tags": ["integration", "area"]},
        {"subject": "Mathematics", "difficulty": "medium", "year": 2024, "source": "JEE Main 2024",
         "question_text": "The number of solutions of the equation sin x = x/10 in the interval [0, 10π] is:",
         "options": {"A": "6", "B": "7", "C": "5", "D": "4"}, "correct_answer": "B",
         "explanation": "The line y=x/10 intersects y=sin(x) at x=0 plus 6 more points in [0, 10π], for a total of 7 solutions.",
         "tags": ["trigonometric equations"]},
    ],

    "JEE Advanced": [
        {"subject": "Physics", "difficulty": "hard", "year": 2023, "source": "JEE Advanced 2023 Paper 1",
         "question_text": "A particle of mass m is projected at 45° with speed v₀ from the top of a smooth inclined plane of inclination 30°. The range on the inclined plane is:",
         "options": {"A": "4v₀²/(3g√3)", "B": "2v₀²/(g√3)", "C": "v₀²√3/g", "D": "4v₀²√3/(3g)"}, "correct_answer": "A",
         "explanation": "Using projectile on inclined plane formula with effective gravity components, R = 2v₀²sin(θ-α)cos(θ)/(g·cos²α) where θ=45°, α=30°.",
         "tags": ["projectile", "inclined plane"]},
        {"subject": "Physics", "difficulty": "hard", "year": 2023, "source": "JEE Advanced 2023 Paper 2",
         "question_text": "Two capacitors C₁ = 2μF and C₂ = 4μF are charged to 100V and 200V respectively, then connected in parallel with like plates together. The final energy stored is:",
         "options": {"A": "0.06 J", "B": "0.08 J", "C": "0.1 J", "D": "0.12 J"}, "correct_answer": "B",
         "explanation": "Common voltage V = (C₁V₁ + C₂V₂)/(C₁+C₂) = (200+800)/6 = 500/3 V. E = ½(C₁+C₂)V² = ½(6×10⁻⁶)(500/3)² ≈ 0.083 J ≈ 0.08 J.",
         "tags": ["capacitors", "electrostatics"]},
        {"subject": "Chemistry", "difficulty": "hard", "year": 2023, "source": "JEE Advanced 2023",
         "question_text": "The number of geometrical isomers possible for [Co(NH₃)₃Cl₃] is:",
         "options": {"A": "2", "B": "3", "C": "4", "D": "1"}, "correct_answer": "A",
         "explanation": "For [MA₃B₃] octahedral complex, there are 2 geometric isomers: fac (facial) and mer (meridional).",
         "tags": ["coordination chemistry", "isomerism"]},
        {"subject": "Mathematics", "difficulty": "hard", "year": 2023, "source": "JEE Advanced 2023",
         "question_text": "Let f: ℝ → ℝ be defined by f(x) = x|x|. Then f is:",
         "options": {"A": "Differentiable everywhere", "B": "Not differentiable at x = 0", "C": "Continuous but not differentiable at x = 0", "D": "Neither continuous nor differentiable at x = 0"}, "correct_answer": "A",
         "explanation": "f(x) = x² for x≥0 and f(x) = -x² for x<0. Both pieces give f'(0) = 0. The function is differentiable everywhere.",
         "tags": ["differentiability", "continuity"]},
        {"subject": "Mathematics", "difficulty": "hard", "year": 2024, "source": "JEE Advanced 2024 Sample",
         "question_text": "The value of ∫₀^(π/2) log(sin x) dx is:",
         "options": {"A": "-(π/2)log 2", "B": "(π/2)log 2", "C": "-π log 2", "D": "π log 2"}, "correct_answer": "A",
         "explanation": "This is a classic definite integral. Using the property ∫₀^(π/2) log(sin x)dx = ∫₀^(π/2) log(cos x)dx, and adding: 2I = ∫₀^(π/2) log(sin 2x/2)dx = -(π/2)log 2, so I = -(π/2)log 2.",
         "tags": ["definite integrals", "properties"]},
    ],

    "NEET UG": [
        {"subject": "Physics", "difficulty": "easy", "year": 2024, "source": "NEET 2024",
         "question_text": "The dimensional formula of Planck's constant is the same as that of:",
         "options": {"A": "Angular momentum", "B": "Linear momentum", "C": "Force", "D": "Energy"}, "correct_answer": "A",
         "explanation": "Planck's constant h has dimensions [ML²T⁻¹], same as angular momentum (L = mvr → [ML²T⁻¹]).",
         "tags": ["units and dimensions"]},
        {"subject": "Chemistry", "difficulty": "easy", "year": 2024, "source": "NEET 2024",
         "question_text": "Which of the following is an example of a Lewis acid?",
         "options": {"A": "BF₃", "B": "NH₃", "C": "H₂O", "D": "NaOH"}, "correct_answer": "A",
         "explanation": "BF₃ is a Lewis acid because B has an incomplete octet and can accept a lone pair of electrons.",
         "tags": ["acids and bases"]},
        {"subject": "Biology", "difficulty": "easy", "year": 2024, "source": "NEET 2024",
         "question_text": "Which organelle is known as the 'powerhouse of the cell'?",
         "options": {"A": "Mitochondria", "B": "Nucleus", "C": "Golgi apparatus", "D": "Endoplasmic reticulum"}, "correct_answer": "A",
         "explanation": "Mitochondria are called the powerhouse of the cell because they produce ATP through oxidative phosphorylation.",
         "tags": ["cell biology"]},
        {"subject": "Biology", "difficulty": "medium", "year": 2024, "source": "NEET 2024",
         "question_text": "The process of formation of mRNA from DNA is called:",
         "options": {"A": "Transcription", "B": "Translation", "C": "Replication", "D": "Transduction"}, "correct_answer": "A",
         "explanation": "Transcription is the process where mRNA is synthesized from a DNA template using RNA polymerase.",
         "tags": ["molecular biology", "gene expression"]},
        {"subject": "Biology", "difficulty": "hard", "year": 2023, "source": "NEET 2023",
         "question_text": "In the Hardy-Weinberg equation p² + 2pq + q² = 1, the term 2pq represents:",
         "options": {"A": "Heterozygous frequency", "B": "Homozygous dominant frequency", "C": "Homozygous recessive frequency", "D": "Allele frequency"}, "correct_answer": "A",
         "explanation": "In Hardy-Weinberg equilibrium, p² = homozygous dominant, 2pq = heterozygous, q² = homozygous recessive genotype frequencies.",
         "tags": ["genetics", "population genetics"]},
        {"subject": "Physics", "difficulty": "medium", "year": 2023, "source": "NEET 2023",
         "question_text": "A convex lens of focal length 20 cm produces a real image at 60 cm from the lens. The object distance is:",
         "options": {"A": "30 cm", "B": "40 cm", "C": "20 cm", "D": "15 cm"}, "correct_answer": "A",
         "explanation": "Using 1/v - 1/u = 1/f, 1/60 - 1/u = 1/20, 1/u = 1/60 - 1/20 = -2/60 = -1/30, u = -30 cm. Object is at 30 cm.",
         "tags": ["optics", "lenses"]},
    ],

    "CBSE 10th": [
        {"subject": "Mathematics", "difficulty": "easy", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "The HCF of 12, 15, and 21 is:",
         "options": {"A": "3", "B": "6", "C": "1", "D": "12"}, "correct_answer": "A",
         "explanation": "12 = 2²×3, 15 = 3×5, 21 = 3×7. Common factor: 3. HCF = 3.",
         "tags": ["number theory", "HCF"]},
        {"subject": "Science", "difficulty": "easy", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "Which gas is produced when dilute hydrochloric acid is added to a reactive metal?",
         "options": {"A": "Hydrogen", "B": "Oxygen", "C": "Carbon dioxide", "D": "Nitrogen"}, "correct_answer": "A",
         "explanation": "Reactive metals react with dilute HCl to produce hydrogen gas. E.g., Zn + 2HCl → ZnCl₂ + H₂↑.",
         "tags": ["chemical reactions", "acids"]},
        {"subject": "English", "difficulty": "easy", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "Choose the correct form of the verb: 'Each of the boys _____ present.'",
         "options": {"A": "was", "B": "were", "C": "are", "D": "have been"}, "correct_answer": "A",
         "explanation": "'Each' is singular and takes a singular verb. 'Each of the boys was present' is correct.",
         "tags": ["grammar", "subject-verb agreement"]},
        {"subject": "SST", "difficulty": "medium", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "The Jallianwala Bagh massacre took place in which year?",
         "options": {"A": "1919", "B": "1920", "C": "1921", "D": "1922"}, "correct_answer": "A",
         "explanation": "The Jallianwala Bagh massacre occurred on 13 April 1919 in Amritsar, when British troops under General Dyer fired on a peaceful gathering.",
         "tags": ["history", "Indian independence"]},
    ],

    "CBSE 12th": [
        {"subject": "Physics", "difficulty": "easy", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "The electric field inside a hollow charged conductor is:",
         "options": {"A": "Zero", "B": "Maximum", "C": "Non-uniform", "D": "Depends on shape"}, "correct_answer": "A",
         "explanation": "By Gauss's law, the electric field inside a hollow charged conductor is zero. All charge resides on the surface.",
         "tags": ["electrostatics", "conductors"]},
        {"subject": "Chemistry", "difficulty": "medium", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "The coordination number of Na⁺ in NaCl crystal is:",
         "options": {"A": "6", "B": "4", "C": "8", "D": "12"}, "correct_answer": "A",
         "explanation": "In NaCl crystal structure, each Na⁺ ion is surrounded by 6 Cl⁻ ions, giving a coordination number of 6.",
         "tags": ["solid state", "crystal structure"]},
        {"subject": "Mathematics", "difficulty": "medium", "year": 2024, "source": "CBSE 2024 Board",
         "question_text": "If y = sin⁻¹(2x/(1+x²)), then dy/dx is:",
         "options": {"A": "2/(1+x²)", "B": "1/(1+x²)", "C": "2x/(1+x²)", "D": "-2/(1+x²)"}, "correct_answer": "A",
         "explanation": "Substituting x = tan θ, y = sin⁻¹(sin 2θ) = 2θ = 2tan⁻¹x. dy/dx = 2/(1+x²).",
         "tags": ["differentiation", "inverse trigonometry"]},
    ],

    "CAT": [
        {"subject": "Quant", "difficulty": "medium", "year": 2023, "source": "CAT 2023",
         "question_text": "A shopkeeper marks the price of an article 40% above the cost price. He allows a discount of 20%. His profit percentage is:",
         "options": {"A": "12%", "B": "20%", "C": "16%", "D": "8%"}, "correct_answer": "A",
         "explanation": "Let CP = 100. MP = 140. SP = 140 × 0.8 = 112. Profit = 12%. Alternatively: (1.4)(0.8) - 1 = 0.12 = 12%.",
         "tags": ["profit and loss", "percentages"]},
        {"subject": "VARC", "difficulty": "medium", "year": 2023, "source": "CAT 2023",
         "question_text": "Choose the word most nearly OPPOSITE in meaning to 'EPHEMERAL':",
         "options": {"A": "Permanent", "B": "Fleeting", "C": "Temporary", "D": "Transient"}, "correct_answer": "A",
         "explanation": "Ephemeral means lasting for a very short time. Its opposite is permanent.",
         "tags": ["vocabulary", "antonyms"]},
        {"subject": "DILR", "difficulty": "hard", "year": 2023, "source": "CAT 2023",
         "question_text": "If all the letters of the word 'MATHEMATICS' are arranged alphabetically, the position of the letter 'T' (first occurrence) would be:",
         "options": {"A": "10th", "B": "9th", "C": "11th", "D": "8th"}, "correct_answer": "A",
         "explanation": "MATHEMATICS sorted: A, A, C, E, H, I, M, M, S, T, T. The first T is at position 10.",
         "tags": ["permutations", "combinatorics"]},
    ],

    "GATE (CS)": [
        {"subject": "DSA", "difficulty": "medium", "year": 2024, "source": "GATE CS 2024",
         "question_text": "The time complexity of building a binary heap from an array of n elements is:",
         "options": {"A": "O(n)", "B": "O(n log n)", "C": "O(n²)", "D": "O(log n)"}, "correct_answer": "A",
         "explanation": "Bottom-up heap construction (heapify) runs in O(n) time, not O(n log n) as a naive analysis might suggest.",
         "tags": ["heap", "time complexity"]},
        {"subject": "OS", "difficulty": "easy", "year": 2024, "source": "GATE CS 2024",
         "question_text": "Which scheduling algorithm is non-preemptive?",
         "options": {"A": "FCFS", "B": "Round Robin", "C": "SRTF", "D": "Priority (preemptive)"}, "correct_answer": "A",
         "explanation": "First Come First Served (FCFS) is inherently non-preemptive — once a process starts executing, it runs to completion.",
         "tags": ["process scheduling"]},
        {"subject": "DBMS", "difficulty": "medium", "year": 2023, "source": "GATE CS 2023",
         "question_text": "A relation R(A, B, C, D) with FDs: A→B, B→C. The highest normal form of R is:",
         "options": {"A": "2NF", "B": "1NF", "C": "3NF", "D": "BCNF"}, "correct_answer": "A",
         "explanation": "Key is AD. A→B (partial dependency since A is part of key), but B→C is transitive. After removing partial dependency, it's in 2NF.",
         "tags": ["normalization", "functional dependencies"]},
        {"subject": "Networks", "difficulty": "easy", "year": 2024, "source": "GATE CS 2024",
         "question_text": "The subnet mask for a Class C network is:",
         "options": {"A": "255.255.255.0", "B": "255.255.0.0", "C": "255.0.0.0", "D": "255.255.255.128"}, "correct_answer": "A",
         "explanation": "Class C addresses use 24 bits for the network portion and 8 bits for hosts, giving a default subnet mask of 255.255.255.0.",
         "tags": ["subnetting", "IP addressing"]},
    ],

    "UPSC Prelims": [
        {"subject": "GS", "difficulty": "medium", "year": 2024, "source": "UPSC Prelims 2024",
         "question_text": "Which of the following is NOT a fundamental right guaranteed by the Indian Constitution?",
         "options": {"A": "Right to Property", "B": "Right to Equality", "C": "Right to Freedom", "D": "Right against Exploitation"}, "correct_answer": "A",
         "explanation": "Right to Property was removed as a fundamental right by the 44th Amendment (1978). It is now a legal right under Article 300A.",
         "tags": ["polity", "fundamental rights"]},
        {"subject": "GS", "difficulty": "easy", "year": 2024, "source": "UPSC Prelims 2024",
         "question_text": "The Tropic of Cancer does NOT pass through which of the following states?",
         "options": {"A": "Odisha", "B": "Rajasthan", "C": "Madhya Pradesh", "D": "Gujarat"}, "correct_answer": "A",
         "explanation": "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, and Mizoram. Odisha is not one of them.",
         "tags": ["geography", "India"]},
        {"subject": "CSAT", "difficulty": "medium", "year": 2023, "source": "UPSC Prelims 2023",
         "question_text": "A clock shows 3:15. What is the angle between the hour and minute hands?",
         "options": {"A": "7.5°", "B": "0°", "C": "15°", "D": "22.5°"}, "correct_answer": "A",
         "explanation": "At 3:15, minute hand is at 90°. Hour hand = 30×3 + 0.5×15 = 90 + 7.5 = 97.5°. Angle = 97.5 - 90 = 7.5°.",
         "tags": ["reasoning", "clock problems"]},
        {"subject": "Current Affairs", "difficulty": "medium", "year": 2024, "source": "UPSC Prelims 2024",
         "question_text": "India's first indigenous aircraft carrier commissioned in 2022 is named:",
         "options": {"A": "INS Vikrant", "B": "INS Viraat", "C": "INS Vikramaditya", "D": "INS Vishal"}, "correct_answer": "A",
         "explanation": "INS Vikrant (IAC-1) was commissioned on 2 September 2022, making India the 6th country to design and build its own aircraft carrier.",
         "tags": ["defence", "current affairs"]},
    ],

    # =========================================================================
    # USA
    # =========================================================================
    "SAT": [
        {"subject": "Math", "difficulty": "easy", "year": 2024, "source": "SAT Practice Test 2024",
         "question_text": "If 3x + 7 = 22, what is the value of x?",
         "options": {"A": "5", "B": "6", "C": "7", "D": "4"}, "correct_answer": "A",
         "explanation": "3x + 7 = 22. 3x = 15. x = 5.",
         "tags": ["algebra", "linear equations"]},
        {"subject": "Math", "difficulty": "medium", "year": 2024, "source": "SAT Practice Test 2024",
         "question_text": "A circle has a circumference of 16π. What is its area?",
         "options": {"A": "64π", "B": "32π", "C": "256π", "D": "16π"}, "correct_answer": "A",
         "explanation": "C = 2πr = 16π, so r = 8. Area = πr² = π(64) = 64π.",
         "tags": ["geometry", "circles"]},
        {"subject": "Reading", "difficulty": "medium", "year": 2024, "source": "SAT Practice Test 2024",
         "question_text": "In the context of a passage about climate change, 'mitigate' most nearly means:",
         "options": {"A": "Lessen the severity of", "B": "Completely eliminate", "C": "Temporarily postpone", "D": "Scientifically measure"}, "correct_answer": "A",
         "explanation": "Mitigate means to make something less severe or serious.",
         "tags": ["vocabulary", "context clues"]},
        {"subject": "Writing", "difficulty": "easy", "year": 2024, "source": "SAT Practice Test 2024",
         "question_text": "Choose the correct sentence: ",
         "options": {"A": "Neither the teacher nor the students were ready.", "B": "Neither the teacher nor the students was ready.", "C": "Neither the teacher nor the students is ready.", "D": "Neither the teacher nor the students has been ready."}, "correct_answer": "A",
         "explanation": "With 'neither...nor', the verb agrees with the nearer subject. 'Students' is plural, so 'were' is correct.",
         "tags": ["grammar", "subject-verb agreement"]},
        {"subject": "Math", "difficulty": "hard", "year": 2023, "source": "SAT Official 2023",
         "question_text": "If f(x) = 2x² - 8x + 3, what is the minimum value of f(x)?",
         "options": {"A": "-5", "B": "-3", "C": "3", "D": "5"}, "correct_answer": "A",
         "explanation": "f(x) = 2(x² - 4x) + 3 = 2(x-2)² - 8 + 3 = 2(x-2)² - 5. Minimum value is -5 at x = 2.",
         "tags": ["algebra", "quadratics"]},
    ],

    "ACT": [
        {"subject": "English", "difficulty": "easy", "year": 2024, "source": "ACT Practice 2024",
         "question_text": "Which of the following is grammatically correct?",
         "options": {"A": "The data show a clear trend.", "B": "The data shows a clear trend.", "C": "The datas show a clear trend.", "D": "The data showing a clear trend."}, "correct_answer": "A",
         "explanation": "'Data' is the plural of 'datum.' The correct verb form is 'show' (plural).",
         "tags": ["grammar"]},
        {"subject": "Math", "difficulty": "medium", "year": 2024, "source": "ACT Practice 2024",
         "question_text": "What is the slope of the line perpendicular to 2x + 3y = 6?",
         "options": {"A": "3/2", "B": "-2/3", "C": "2/3", "D": "-3/2"}, "correct_answer": "A",
         "explanation": "2x + 3y = 6 → y = -2x/3 + 2. Slope = -2/3. Perpendicular slope = 3/2.",
         "tags": ["coordinate geometry", "slopes"]},
        {"subject": "Science", "difficulty": "medium", "year": 2024, "source": "ACT Practice 2024",
         "question_text": "During photosynthesis, which gas is absorbed by plants?",
         "options": {"A": "Carbon dioxide", "B": "Oxygen", "C": "Nitrogen", "D": "Hydrogen"}, "correct_answer": "A",
         "explanation": "Plants absorb CO₂ during photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.",
         "tags": ["biology", "photosynthesis"]},
        {"subject": "Reading", "difficulty": "easy", "year": 2024, "source": "ACT Practice 2024",
         "question_text": "The word 'ubiquitous' most nearly means:",
         "options": {"A": "Found everywhere", "B": "Very rare", "C": "Extremely large", "D": "Highly complex"}, "correct_answer": "A",
         "explanation": "Ubiquitous means present, appearing, or found everywhere.",
         "tags": ["vocabulary"]},
    ],

    "AP Calculus AB": [
        {"subject": "Limits", "difficulty": "easy", "year": 2024, "source": "AP Calculus AB 2024",
         "question_text": "lim(x→2) (x² - 4)/(x - 2) equals:",
         "options": {"A": "4", "B": "2", "C": "0", "D": "Does not exist"}, "correct_answer": "A",
         "explanation": "(x² - 4)/(x - 2) = (x+2)(x-2)/(x-2) = x + 2. As x→2, this equals 4.",
         "tags": ["limits", "factoring"]},
        {"subject": "Derivatives", "difficulty": "medium", "year": 2024, "source": "AP Calculus AB 2024",
         "question_text": "If f(x) = ln(x²+1), then f'(x) is:",
         "options": {"A": "2x/(x²+1)", "B": "1/(x²+1)", "C": "2x·ln(x²+1)", "D": "x/(x²+1)"}, "correct_answer": "A",
         "explanation": "By chain rule: f'(x) = [1/(x²+1)] · 2x = 2x/(x²+1).",
         "tags": ["derivatives", "chain rule"]},
        {"subject": "Integrals", "difficulty": "medium", "year": 2024, "source": "AP Calculus AB 2024",
         "question_text": "∫ sin(2x) dx equals:",
         "options": {"A": "-½cos(2x) + C", "B": "½cos(2x) + C", "C": "-cos(2x) + C", "D": "2cos(2x) + C"}, "correct_answer": "A",
         "explanation": "Using u-substitution: u = 2x, du = 2dx. ∫sin(u) · du/2 = -½cos(u) + C = -½cos(2x) + C.",
         "tags": ["integration", "u-substitution"]},
        {"subject": "Derivatives", "difficulty": "hard", "year": 2023, "source": "AP Calculus AB 2023",
         "question_text": "If xy + y² = 1, find dy/dx at the point (0, 1):",
         "options": {"A": "-1/2", "B": "1/2", "C": "-1", "D": "0"}, "correct_answer": "A",
         "explanation": "Implicit differentiation: y + xy' + 2yy' = 0. y'(x + 2y) = -y. y' = -y/(x+2y). At (0,1): y' = -1/(0+2) = -1/2.",
         "tags": ["implicit differentiation"]},
    ],

    "AP Physics 1": [
        {"subject": "Mechanics", "difficulty": "easy", "year": 2024, "source": "AP Physics 1 2024",
         "question_text": "A 5 kg object is at rest on a frictionless surface. A 10 N force is applied. The acceleration is:",
         "options": {"A": "2 m/s²", "B": "5 m/s²", "C": "10 m/s²", "D": "0.5 m/s²"}, "correct_answer": "A",
         "explanation": "F = ma. a = F/m = 10/5 = 2 m/s².",
         "tags": ["Newton's laws", "forces"]},
        {"subject": "Waves", "difficulty": "medium", "year": 2024, "source": "AP Physics 1 2024",
         "question_text": "The speed of sound in air at 20°C is approximately 343 m/s. What is the wavelength of a 686 Hz sound wave?",
         "options": {"A": "0.5 m", "B": "1 m", "C": "2 m", "D": "0.25 m"}, "correct_answer": "A",
         "explanation": "v = fλ. λ = v/f = 343/686 = 0.5 m.",
         "tags": ["waves", "sound"]},
        {"subject": "Circuits", "difficulty": "medium", "year": 2024, "source": "AP Physics 1 2024",
         "question_text": "Three 6Ω resistors are connected in parallel. The equivalent resistance is:",
         "options": {"A": "2 Ω", "B": "18 Ω", "C": "6 Ω", "D": "3 Ω"}, "correct_answer": "A",
         "explanation": "1/R_eq = 1/6 + 1/6 + 1/6 = 3/6 = 1/2. R_eq = 2 Ω.",
         "tags": ["circuits", "resistance"]},
    ],

    "AP Chemistry": [
        {"subject": "Atomic", "difficulty": "easy", "year": 2024, "source": "AP Chemistry 2024",
         "question_text": "An atom of ²³Na has how many neutrons?",
         "options": {"A": "12", "B": "11", "C": "23", "D": "13"}, "correct_answer": "A",
         "explanation": "Na has atomic number 11. Neutrons = Mass number - Atomic number = 23 - 11 = 12.",
         "tags": ["atomic structure"]},
        {"subject": "Bonding", "difficulty": "medium", "year": 2024, "source": "AP Chemistry 2024",
         "question_text": "What type of intermolecular force is primarily responsible for the high boiling point of water?",
         "options": {"A": "Hydrogen bonding", "B": "London dispersion forces", "C": "Dipole-dipole forces", "D": "Ion-dipole forces"}, "correct_answer": "A",
         "explanation": "Water's high boiling point is primarily due to strong hydrogen bonding between water molecules (O-H···O).",
         "tags": ["intermolecular forces"]},
        {"subject": "Reactions", "difficulty": "medium", "year": 2024, "source": "AP Chemistry 2024",
         "question_text": "In the reaction 2H₂O₂ → 2H₂O + O₂, the oxidation state of oxygen changes from:",
         "options": {"A": "-1 to -2 and 0", "B": "-2 to 0", "C": "0 to -2", "D": "-1 to -1"}, "correct_answer": "A",
         "explanation": "In H₂O₂, O is -1. In H₂O, O is -2. In O₂, O is 0. This is a disproportionation reaction.",
         "tags": ["redox", "oxidation states"]},
    ],

    "GRE": [
        {"subject": "Quant", "difficulty": "medium", "year": 2024, "source": "GRE Official Guide",
         "question_text": "If the average of five numbers is 20 and one number is removed, the average becomes 18, then the removed number is:",
         "options": {"A": "28", "B": "24", "C": "20", "D": "32"}, "correct_answer": "A",
         "explanation": "Sum of 5 numbers = 100. Sum of 4 numbers = 72. Removed number = 100 - 72 = 28.",
         "tags": ["averages", "statistics"]},
        {"subject": "Verbal", "difficulty": "medium", "year": 2024, "source": "GRE Official Guide",
         "question_text": "Select the word most similar in meaning to 'PERFIDIOUS':",
         "options": {"A": "Treacherous", "B": "Perfect", "C": "Permanent", "D": "Performing"}, "correct_answer": "A",
         "explanation": "Perfidious means deceitful and untrustworthy, i.e., treacherous.",
         "tags": ["vocabulary", "synonyms"]},
        {"subject": "Quant", "difficulty": "hard", "year": 2024, "source": "GRE Official Guide",
         "question_text": "How many integers from 1 to 100 are divisible by 3 but not by 5?",
         "options": {"A": "27", "B": "33", "C": "20", "D": "30"}, "correct_answer": "A",
         "explanation": "Divisible by 3: floor(100/3) = 33. Divisible by both 3 and 5 (i.e., 15): floor(100/15) = 6. Answer: 33 - 6 = 27.",
         "tags": ["number theory", "divisibility"]},
    ],

    "GMAT": [
        {"subject": "Quant", "difficulty": "medium", "year": 2024, "source": "GMAT Official Guide",
         "question_text": "If a train travels 300 km in 4 hours and then 200 km in 3 hours, what is the average speed for the entire journey?",
         "options": {"A": "71.4 km/h", "B": "75 km/h", "C": "72 km/h", "D": "70 km/h"}, "correct_answer": "A",
         "explanation": "Total distance = 500 km. Total time = 7 hours. Average speed = 500/7 ≈ 71.4 km/h.",
         "tags": ["speed", "average"]},
        {"subject": "Verbal", "difficulty": "medium", "year": 2024, "source": "GMAT Official Guide",
         "question_text": "Choose the sentence that is grammatically correct:",
         "options": {"A": "If I were you, I would accept the offer.", "B": "If I was you, I would accept the offer.", "C": "If I were you, I will accept the offer.", "D": "If I was you, I will accept the offer."}, "correct_answer": "A",
         "explanation": "The subjunctive mood requires 'were' for contrary-to-fact conditions: 'If I were you' with 'would' in the main clause.",
         "tags": ["grammar", "subjunctive"]},
        {"subject": "IR", "difficulty": "medium", "year": 2024, "source": "GMAT Official Guide",
         "question_text": "A dataset has values: 10, 15, 20, 25, 30. The standard deviation is closest to:",
         "options": {"A": "7.07", "B": "5", "C": "10", "D": "8.5"}, "correct_answer": "A",
         "explanation": "Mean = 20. Deviations: -10,-5,0,5,10. Variance = (100+25+0+25+100)/5 = 50. SD = √50 ≈ 7.07.",
         "tags": ["statistics", "standard deviation"]},
    ],

    # =========================================================================
    # CHINA
    # =========================================================================
    "高考 (Gaokao)": [
        {"subject": "数学", "difficulty": "medium", "year": 2024, "source": "高考 2024 全国卷",
         "question_text": "设函数 f(x) = x³ - 3x，则 f(x) 的极小值为：",
         "options": {"A": "-2", "B": "2", "C": "-3", "D": "0"}, "correct_answer": "A",
         "explanation": "f'(x) = 3x² - 3 = 0，x = ±1。f''(x) = 6x。f''(1) = 6 > 0，x=1是极小值点。f(1) = 1 - 3 = -2。",
         "tags": ["calculus", "extrema"]},
        {"subject": "英语", "difficulty": "easy", "year": 2024, "source": "高考 2024 英语",
         "question_text": "Choose the correct form: 'I wish I _____ harder last semester.'",
         "options": {"A": "had studied", "B": "studied", "C": "have studied", "D": "would study"}, "correct_answer": "A",
         "explanation": "After 'wish', past contrary-to-fact situations use the past perfect: 'had studied'.",
         "tags": ["grammar", "subjunctive"]},
        {"subject": "语文", "difficulty": "medium", "year": 2024, "source": "高考 2024 语文",
         "question_text": "下列词语中，没有错别字的一项是：",
         "options": {"A": "名副其实", "B": "名符其实", "C": "名幅其实", "D": "明副其实"}, "correct_answer": "A",
         "explanation": "正确写法是'名副其实'，意为名声与实际相符合。",
         "tags": ["字词", "成语"]},
    ],

    "中考 (Zhongkao)": [
        {"subject": "数学", "difficulty": "easy", "year": 2024, "source": "中考 2024",
         "question_text": "一元二次方程 x² - 5x + 6 = 0 的两个根是：",
         "options": {"A": "2 和 3", "B": "1 和 6", "C": "-2 和 -3", "D": "5 和 1"}, "correct_answer": "A",
         "explanation": "x² - 5x + 6 = (x-2)(x-3) = 0，所以 x = 2 或 x = 3。",
         "tags": ["algebra", "quadratic equations"]},
        {"subject": "英语", "difficulty": "easy", "year": 2024, "source": "中考 2024",
         "question_text": "Choose the correct answer: 'She _____ to school every day.'",
         "options": {"A": "walks", "B": "walk", "C": "walking", "D": "walked"}, "correct_answer": "A",
         "explanation": "Third person singular present tense with 'every day' requires 'walks'.",
         "tags": ["grammar", "tenses"]},
        {"subject": "物理", "difficulty": "medium", "year": 2024, "source": "中考 2024",
         "question_text": "一个标有 '220V 100W' 的灯泡，正常工作时的电流约为：",
         "options": {"A": "0.45 A", "B": "0.22 A", "C": "2.2 A", "D": "4.5 A"}, "correct_answer": "A",
         "explanation": "P = UI，I = P/U = 100/220 ≈ 0.45 A。",
         "tags": ["electricity", "power"]},
        {"subject": "化学", "difficulty": "easy", "year": 2024, "source": "中考 2024",
         "question_text": "下列物质中，属于氧化物的是：",
         "options": {"A": "H₂O", "B": "NaCl", "C": "O₂", "D": "KMnO₄"}, "correct_answer": "A",
         "explanation": "氧化物是由两种元素组成，其中一种是氧的化合物。H₂O 由 H 和 O 两种元素组成，是氧化物。",
         "tags": ["classification", "oxides"]},
    ],
}
